version: '3'

services:
  servidor:
    build: ./app_servidor
    ports:
      - "5000:5000"

  carro:
    build: ./app_carro
    depends_on:
      - servidor

  ponto_recarga:
    build: ./app_ponto_recarga
    depends_on:
      - servidor
